// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OZON_Delivery_checker.Data;

#nullable disable

namespace OZON_Delivery_checker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250127090350_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("OZON_Delivery_checker.Data.RequestRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryDateBegin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryDateEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryDatePeriodChangedMoment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RequestRecords");
                });

            modelBuilder.Entity("OZON_Delivery_checker.DataBase.RequestEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Moment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestRecordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RequestRecordId");

                    b.ToTable("RequestEvents");
                });

            modelBuilder.Entity("OZON_Delivery_checker.DataBase.RequestEvent", b =>
                {
                    b.HasOne("OZON_Delivery_checker.Data.RequestRecord", "RequestRecord")
                        .WithMany()
                        .HasForeignKey("RequestRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
